### PR TITLE
fix #32 - no error messages on CLI

### LINKED ISSUE #32: no error messages
```
$ ./drepl
[D> audo r = 4;
[D> hgurelsdgjfds
[D>
```

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by wilzbach** [comment]
> /usr/bin/ld: cannot find -llinenoise
> collect2: ld returned 1 exit status

**Comment by wilzbach** [comment]
rebase and then Travis will stop complaining?

**Comment by MartinNowak** [comment]
done

**Comment by MartinNowak** [comment]
Colorize seems to be the most widely used dub library for coloring, see https://code.dlang.org/api/packages/colorize/stats.

**Comment by wilzbach** [comment]
> Colorize seems to be the most widely used dub library for coloring, see

works nicely :)

**Pull request merged**
